=== aresmendi/1-DAM-2024-2025/Lenguaje_de_Marcas/Practica 3.1/Validaciones/1.Canciones.dtd
<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion (duracion?, año, compositores, disco?, sello?, artistas)>
<!ATTLIST cancion
  titulo ID #REQUIRED>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT compositores (compositor+)>
<!ELEMENT compositor (nombre, apellidos?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT disco (#PCDATA)>
<!ELEMENT sello (#PCDATA)>
<!ELEMENT artistas (artista+)>
<!ELEMENT artista (#PCDATA)>

=== aresmendi/1-DAM-2024-2025/Lenguaje_de_Marcas/Practica 3.1/1.Canciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE canciones SYSTEM "1.Canciones.dtd">
<canciones>
  <cancion titulo="VideoKilledTheRadioStar">
    <duracion>4.08</duracion>
    <año>1979</año>
    <compositores>
      <compositor>
        <nombre>Geoff</nombre>
        <apellidos>Downes</apellidos>
      </compositor>
      <compositor>
        <nombre>Trevor</nombre>
        <apellidos>Horn</apellidos>
      </compositor>
      <compositor>
        <nombre>Bruce</nombre>
        <apellidos>Woolley</apellidos>
      </compositor>
    </compositores>
    <disco>The Age of Plastic</disco>
    <sello>Island</sello>
    <artistas>
      <artista>Buggles</artista>
    </artistas>
  </cancion>
</canciones>
