=== aresmendi/1-DAM-2024-2025/Lenguaje_de_Marcas/Practica 3.1/Validaciones/2.Correos.dtd
<!ELEMENT mensaje (remitente, destinatario+,asunto,cuerpo)>
<!ELEMENT remitente (nombre?, email)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ATTLIST destinatario 
  nombre CDATA #IMPLIED
  email CDATA #REQUIRED>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT cuerpo (parrafo*)>
<!ELEMENT parrafo (#PCDATA)>

=== aresmendi/1-DAM-2024-2025/Lenguaje_de_Marcas/Practica 3.1/2.Correos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE canciones SYSTEM "2.Correos.dtd">
<mensaje>
  <remitente>
    <nombre>"Will Smith"</nombre>
	<email>"will@overbrookent.com"</email>
  </remitente>
  <destinatario
    nombre="Chris Rock"
	email="chrissy@chrisrock.com"/>
  
  <asunto> Hola Chris </asunto>
  <cuerpo>
    <parrafo> Hola ¿que tal? </parrafo>
	<parrafo> Oye, que no me contestas los guasaps. A ver si me llamas y quedamos </parrafo>
	<parrafo> Un saludo </parrafo>
  </cuerpo>
</mensaje>
