<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE recetas [
	<!ELEMENT recetas (receta+)> 
	<!ELEMENT receta (nombre, ingredientes, preparacion)>
	<!ATTLIST receta
	numRaciones CDATA #REQUIRED
	dificultad (facil|medio|dificil) "medio">
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT ingredientes (ingrediente+)>
	<!ELEMENT ingrediente (#PCDATA)>
	<!ATTLIST ingrediente
	cantidad CDATA #IMPLIED
	unidad CDATA #IMPLIED>
	<!ELEMENT preparacion (#PCDATA)>
]>

<recetas>
<receta numRaciones="1">
<nombre>Pan con ajo y perejil</nombre>
<ingredientes>
<ingrediente>Pan</ingrediente>
<ingrediente>Ajo</ingrediente>
<ingrediente cantidad="1" unidad="puñao">Perejil</ingrediente>
</ingredientes>
<preparacion>Cortar el pan en rebanadas; tostarlo; pelar el ajo; fortarlo en el pan; trocear el perejil; espolvorear sobre el pan</preparacion>
</receta>
</recetas>