=== aresmendi/1-DAM-2024-2025/Lenguaje_de_Marcas/XSD Recuperacion/XSD/juegos.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!--RAIZ-->
	<xs:element name="videojuegos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="juego" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- RESTRICCIONES -->
	<xs:simpleType name="codigo">
		<xs:restriction base="xs:ID">
			<xs:pattern value="MG[0-9]{6}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="persona">
		<xs:restriction base="xs:string">
			<xs:maxLength value="40"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="genero">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Accion"/>
			<xs:enumeration value="Aventura"/>
			<xs:enumeration value="Azar"/>
			<xs:enumeration value="Conduccion"/>
			<xs:enumeration value="Deportes"/>
			<xs:enumeration value="Educativo"/>
			<xs:enumeration value="Estrategia"/>
			<xs:enumeration value="Puzzle"/>
			<xs:enumeration value="RPG"/>
			<xs:enumeration value="Simulacion"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="gameplay">
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="plataforma">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PlayStation 4"/>
			<xs:enumeration value="Xbox One"/>
			<xs:enumeration value="Xbox"/>
			<xs:enumeration value="PlayStation 2"/>
			<xs:enumeration value="Windows"/>
			<xs:enumeration value="PlayStation 3"/>
			<xs:enumeration value="PlayStation Vita"/>
			<xs:enumeration value="Macintosh"/>
			<xs:enumeration value="Xbox 360"/>
			<xs:enumeration value="Switch"/>
			<xs:enumeration value="Linux"/>
			<xs:enumeration value="PlayStation 5"/>
			<xs:enumeration value="Xbox Series"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="pegi">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="3"/>
			<xs:enumeration value="7"/>
			<xs:enumeration value="12"/>
			<xs:enumeration value="16"/>
			<xs:enumeration value="18"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="metacritic">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="mobyScore">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="10"/>
			<xs:fractionDigits value="1"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- ELEMENTO juego -->

	<xs:element name="juego">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="titulo" type="xs:string"/>
				<xs:element name="desarrollo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="estudio" type="xs:string" minOccurs="0"/>
							<xs:element name="direccion">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="director" type="persona" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

							<xs:element name="produccion">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="productor" type="persona" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="guion" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="guionista" type="persona" maxOccurs="unbounded" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="publicacion" type="xs:date"/>
				<xs:element name="genero" type="genero"/>
				<xs:element name="gameplays">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="gameplay" type="gameplay" maxOccurs="3"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="plataformas">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="plataforma" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="nombre" type="plataforma" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="pegi" type="pegi"/>
				<xs:choice>
					<xs:element name="metacritic" type="metacritic"/>
					<xs:element name="mobyscore" type="mobyScore"/>
				</xs:choice>
				<xs:element name="paisOrigen" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="codigo" type="codigo" use="required"/>
		</xs:complexType>
	</xs:element>



</xs:schema>

=== aresmendi/1-DAM-2024-2025/Lenguaje_de_Marcas/XSD Recuperacion/juegos.xml
<?xml version='1.0' encoding='utf-8'?>
<videojuegos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD\juegos.xsd">
	<juego codigo="MG007715">
		<titulo>Metal Gear Solid 2: Substance</titulo>
		<desarrollo>
			<estudio>Konami CEJ</estudio>
			<direccion>
				<director>Hideo Kojima</director>
			</direccion>
			<produccion>
				<productor>Hideo Kojima</productor>
			</produccion>
			<guion>
				<guionista>Hideo Kojima</guionista>
			</guion>
		</desarrollo>
		<publicacion>2002-11-05</publicacion>
		<genero>Accion</genero>
		<gameplays>
			<gameplay>Shooter</gameplay>
			<gameplay>Stealth</gameplay>
		</gameplays>
		<plataformas>
			<plataforma nombre="Xbox" />
			<plataforma nombre="PlayStation 2"/>
			<plataforma nombre="Windows"/>
			<plataforma nombre="PlayStation 3"/>
			<plataforma nombre="PlayStation Vita"/>
		</plataformas>
		<pegi>16</pegi>
		<metacritic>87</metacritic>
		<paisOrigen>Japon</paisOrigen>
	</juego>
	<juego codigo="MG053072">
		<titulo>The Binding of Isac</titulo>
		<desarrollo>
			<estudio/>
			<direccion>
				<director>Edmund McMilen</director>
				<director>Florian Himsl</director>
			</direccion>
			<produccion>
				<productor>Edmund McMillen</productor>
				<productor>Florian Himsl</productor>
			</produccion>
			<guion>
				<guionista> Edmund McMillen</guionista>
				<guionista>Florian Himsl</guionista>
			</guion>
		</desarrollo>
		<publicacion>2011-09-28</publicacion>
		<genero>Accion</genero>
		<gameplays>
			<gameplay>Roguelike</gameplay>
			<gameplay>Shooter</gameplay>
		</gameplays>
		<plataformas>
			<plataforma nombre="Windows"/>
			<plataforma nombre="Macintosh"/>
		</plataformas>
		<pegi>16</pegi>
		<metacritic>84</metacritic>
		<paisOrigen>Estados Unidos</paisOrigen>
	</juego>
	<juego codigo="MG049724">
		<titulo>Castlevania: Lors of Shadow</titulo>
		<desarrollo>
			<estudio>MercurySteam</estudio>
			<direccion>
				<director>Enric Alvarez</director> 
			</direccion>
			<produccion>
				<productor>Jose Raluy</productor> 
				<productor>Dave Cox</productor>
				<productor>Hideo Kojima</productor>
			</produccion>
			<guion>
				<guionista>Enric Alvarez</guionista> 
				<guionista>Dave Cox</guionista>
				<guionista>Eddie Deighton</guionista>
			</guion>
		</desarrollo>
		<publicacion>2010-10-05</publicacion>
		<genero>Accion</genero>
		<gameplays>
			<gameplay> Hack and slash</gameplay>
			<gameplay>Puzzle</gameplay>
		</gameplays>
		<plataformas>
			<plataforma nombre="Xbox 360"/>
			<plataforma nombre="PlayStation 3"/>
		</plataformas>
		<pegi>16</pegi>
		<metacritic>83</metacritic>
		<paisOrigen>España</paisOrigen>
	</juego>
	<juego codigo="MG087551">
		<titulo>Mario Kart 8 Deluxe</titulo>
		<desarrollo>
			<estudio>Nintendo EAD</estudio>
			<direccion>
				<director>Yusuke Shiraiwa</director> 
			</direccion>
			<produccion>
				<productor>Hideki Konno</productor>
				<productor>Kosuke Yabuki</productor>
			</produccion>
			<guion/>
		</desarrollo>
		<publicacion>2017-04-28</publicacion>
		<genero>Conduccion</genero>
		<gameplays>
			<gameplay>Arcade</gameplay>
		</gameplays>
		<plataformas>
			<plataforma nombre="Switch" />
		</plataformas>
		<pegi>3</pegi>
		<metacritic>92</metacritic>
		<paisOrigen>Japon</paisOrigen>
	</juego>
	<juego codigo="MG191783">
		<titulo>Return to Monkey Island</titulo>
		<desarrollo>
			<estudio>Terrible Toybox</estudio>
			<direccion>
				<director>Ron Gilbert</director>
				<director>Dave Grossman</director>
			</direccion>
			<produccion>
				<productor>Jenn Sandercock</productor> 
			</produccion>
			<guion>
				<guionista>Dave Grossman</guionista>
				<guionista>Ron Gilbert</guionista>
			</guion>
		</desarrollo>
		<publicacion>2022-09-19</publicacion>
		<genero>Aventura</genero>
		<gameplays>
			<gameplay>Graphic Adventure</gameplay>
			<gameplay>Puzzle</gameplay>
		</gameplays>
		<plataformas>
			<plataforma nombre="Windows"/>
			<plataforma nombre="Macintosh"/>
			<plataforma nombre="Linux"/>
			<plataforma nombre="Switch"/>
			<plataforma nombre="PlayStation 5"/>
			<plataforma nombre="Xbox Series"/>
		</plataformas>
		<pegi>12</pegi>
		<mobyscore>8.4</mobyscore>
		<paisOrigen>Estados Unidos</paisOrigen>
	</juego>
</videojuegos>
